label: 'Hồ sơ'
display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          submit_button: 'Áp dụng'
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      arguments:
        uid:
          exception:
            title: 'Tất cả'
        type:
          exception:
            title: 'Tất cả'
        status:
          exception:
            title: 'Tất cả'
      title: 'Hồ sơ'
