display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          submit_button: Lọc
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
          tags:
            previous: '‹ trước'
            next: 'sau ›'
      fields:
        type:
          label: Kiểu
        mail:
          label: 'Thư điện tử'
        total_price__number:
          label: Tổng
        changed:
          label: 'Đã cập nhật'
        operations:
          label: 'Thao tác'
      filters:
        type:
          expose:
            label: Kiểu
  page_1:
    display_title: Trang
