<?php

use Drupal\image\Entity\ImageStyle;

/**
 * Implements theme_preprocess_field()
 *
*/
function spectre_preprocess_field(&$variables, $hook) {
  $element = $variables['element'];
  $items = $element['#items'];
  $object = $element['#object'];
  //Add some class for field_link in slide paragraph
  if ($element['#field_name'] == 'field_link' && $element['#bundle'] == 'slide') {
    foreach ($variables['items'] as $key => $value) {
      if (is_numeric($key)) {
        $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'link--arrow link--arrow__cicle-blig';
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function spectre_preprocess_paragraph(&$variables) {
  $entity = $variables['paragraph'];
  $entity_bundle = $entity->bundle();
  switch ($entity_bundle) {
    case 'cta':
      if (isset($variables['content']['field_link'][0])) {
        $variables['content']['field_link'][0]['#options']['attributes']['class'] = array('link--arrow link--arrow__cicle-blig');
      }
      break;
    case 'slide':
      // We repare value.
      if (isset($variables['content']['field_image'][0]['#item'])) {
        $item = $variables['content']['field_image'][0]['#item'];
        $variables['content']['field_image'][0]['#item_attributes']['data-title'] = $item->get('title')->getString();
        $style = ImageStyle::load('thumbnail');
        $uri = $item->entity->getFileUri();
        $data_thumb = $style->buildUrl($uri);
        $variables['content']['field_image'][0]['#item_attributes']['data-thumb'] = $data_thumb;
        if (isset($variables['content']['field_image'][1])) {
          $style = ImageStyle::load($variables['content']['field_image'][1]['#image_style']);
          $uri = $variables['content']['field_image'][1]['#item']->entity->getFileUri();
          $variables['content']['field_image']['image_tablet_url'] = $style->buildUrl($uri);
        }
      }
      break;
    default:
      # code...
      break;
  }
}
