css:
  brotli: true
  combine_media: false
  fix_type: true
  preserve_external: false
dns_prefetch: false
path:
  convert:
    absolute_to_protocol_relative: true
    force_https: false
    absolute: false
cache_level: 2
cron_frequency: 86400
enabled: false
global_counter: 0
immutable: true
js:
  brotli: true
  fix_type: true
  preserve_external: false
skip_enabled_preprocess_check: false
show_bypass_cookie_message: true
symlinksifownermatch: false
_core:
  default_config_hash: LFpTzax3EkpWcr8wETN-b7cPB2y6qag7icW86Z-_iiY
langcode: vi
symlinks: false
