progress:
  '#changed': 1505483063
  '#changed_by': '1'
  '#completed_items': 45
  '#items':
    install_and_enable_seo_checklist_module:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_coffee_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_coffee_module:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_admin_toolbar_module:
      '#completed': 1505483063
      '#uid': '1'
    install_composer_command_line_tool:
      '#completed': 1505483063
      '#uid': '1'
    install_console_command_line_tool:
      '#completed': 1505483063
      '#uid': '1'
    install_drush_command_line_tool:
      '#completed': 1505483063
      '#uid': '1'
    show_cli_commands:
      '#completed': 1505483063
      '#uid': '1'
    enable_clean_urls:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_redirect_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_the_redirect_module:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_pathauto_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_pathauto_module:
      '#completed': 1505483063
      '#uid': '1'
    create_pathauto_patterns:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_metatag_module:
      '#completed': 1505483063
      '#uid': '1'
    set_metatags_for_your_site:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_alternate_hreflang_module:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_xml_sitemap_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_xml_sitemap_module:
      '#completed': 1505483063
      '#uid': '1'
    set_up_cron:
      '#completed': 1505483063
      '#uid': '1'
    get_a_google_account:
      '#completed': 1505483063
      '#uid': '1'
    verify_with_google_search_console:
      '#completed': 1505483063
      '#uid': '1'
    submit_xml_sitemap_to_google:
      '#completed': 1505483063
      '#uid': '1'
    get_a_microsoft_account:
      '#completed': 1505483063
      '#uid': '1'
    authenticate_with_bing:
      '#completed': 1505483063
      '#uid': '1'
    submit_xml_sitemap_to_bing:
      '#completed': 1505483063
      '#uid': '1'
    add_xml_sitemap_to_your_robotstxt_file:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_google_analytics_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_google_analytics_module:
      '#completed': 1505483063
      '#uid': '1'
    sign_in_to_google_analytics_and_create_an_analytics_property_for_your_website:
      '#completed': 1505483063
      '#uid': '1'
    verify_your_site_is_sending_data_to_google_analytics:
      '#completed': 1505483063
      '#uid': '1'
    cache_the_google_analytics_code:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_yoast_seo_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_yoast_seo_module:
      '#completed': 1505483063
      '#uid': '1'
    secure_your_website_with_https:
      '#completed': 1505483063
      '#uid': '1'
    adjust_performance_admin_settings:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_advanced_css_js_aggregation_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_advanced_cssjs_aggregation_module:
      '#completed': 1505483063
      '#uid': '1'
    configure_image_styles:
      '#completed': 1505483063
      '#uid': '1'
    move_to_fast_hosting:
      '#completed': 1505483063
      '#uid': '1'
    make_sure_website_is_responsive:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_amp_module_theme_and_php_library_using_composer:
      '#completed': 1505483063
      '#uid': '1'
    configure_amp:
      '#completed': 1505483063
      '#uid': '1'
    install_and_enable_share_buttons_by_addtoany:
      '#completed': 1505483063
      '#uid': '1'
    configure_share_buttons_by_addtoany:
      '#completed': 1505483063
      '#uid': '1'
