label: News
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          separator: ', '
      title: 'Tin Công Nghệ'
  block_1:
    display_title: 'Latest news'
    display_options:
      title: Latest
      fields:
        field_image:
          separator: ', '
        created:
          separator: ', '
        title:
          separator: ', '
        uid:
          alter:
            text: 'Posted by {{ uid }} on {{ created }}'
          separator: ', '
  block_2:
    display_title: Archive
    display_options:
      title: Archives
      arguments:
        created_year_month:
          exception:
            title: All
  block_3:
    display_title: 'Related news'
    display_options:
      title: Related
      fields:
        title:
          separator: ', '
      arguments:
        tid:
          exception:
            title: All
        nid:
          exception:
            title: All
  page_1:
    display_title: Page
